# Generated by Django 4.2.5 on 2023-10-25 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(null=True)),
                ('recipient_room_id', models.CharField()),
                ('message_type', models.CharField(choices=[('SM', 'Self Message'), ('DM', 'Direct Message'), ('GM', 'Group Message')], default='DM', max_length=2)),
                ('message_body', models.CharField(max_length=500)),
                ('sender_timestamp', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receipient_received_from_server_timestamp', models.DateTimeField(null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
