# Generated by Django 4.2.4 on 2023-12-03 16:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOtpAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=12)),
                ('no_of_generation_tries', models.IntegerField(default=0)),
                ('no_of_verification_tries', models.IntegerField(default=0)),
                ('action', models.CharField(choices=[('verify_email', 'V-E')])),
                ('payload', models.JSONField(default=dict)),
                ('used', models.BooleanField(default=False)),
                ('ip_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
