# Generated by Django 4.2.5 on 2023-09-30 14:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ip_addresses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.GenericIPAddressField(),
                default=["127.0.0.1"],
                size=None,
            ),
            preserve_default=False,
        ),
    ]
