# Generated by Django 4.2.5 on 2023-10-25 08:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_ip_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOtpForVerifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=12)),
                ('no_of_generation_tries', models.IntegerField(default=1)),
                ('no_of_verification_tries', models.IntegerField(default=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('ip_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
