# Generated by Django 4.2.5 on 2023-10-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_options_user_activated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailOtpForVerifications',
            new_name='EmailOtpForVerification',
        ),
    ]
