# Generated by Django 4.2.5 on 2023-10-25 11:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_emailotpforverifications_emailotpforverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotpforverification',
            name='ip_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), default=list, size=None),
        ),
    ]
