# Generated by Django 4.2.5 on 2023-11-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_emailotpforverification_ip_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('image_location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/<django.db.models.fields.BigIntegerField>/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='emailotpforverification',
            name='no_of_generation_tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailotpforverification',
            name='no_of_verification_tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailotpforverification',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
