# Generated by Django 4.2.4 on 2023-12-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_artisangeolocation_user_birth_date_user_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtisanGeolocation',
            new_name='UserGeolocation',
        ),
        migrations.DeleteModel(
            name='EmailOtpForVerification',
        ),
    ]
