# Generated by Django 4.2.5 on 2023-09-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='name',
        ),
        migrations.AddField(
            model_name='services',
            name='service_code',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='service_name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
