# Generated by Django 4.2.5 on 2023-10-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_remove_services_name_services_service_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
