# Generated by Django 4.2.5 on 2023-11-12 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("artisans", "0003_delete_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_code", models.CharField(max_length=100)),
                ("service_name", models.CharField(max_length=100)),
                ("service_group_name", models.CharField(max_length=100)),
                ("icon_name", models.CharField(max_length=50)),
                ("icon_color", models.CharField(max_length=7)),
                ("icon_back_drop_color", models.CharField(max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="artisan",
            old_name="description",
            new_name="bio",
        ),
        migrations.AddField(
            model_name="artisan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artisan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="artisan",
            name="services",
            field=models.ManyToManyField(to="artisans.service"),
        ),
        migrations.DeleteModel(
            name="Services",
        ),
    ]
