# Generated by Django 4.2.5 on 2023-11-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0005_artisan_country_artisan_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_individual_name',
            field=models.CharField(default='nothing', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artisan',
            name='country',
            field=models.CharField(choices=[('NG', 'Nigeria')], default='NG', max_length=2),
        ),
    ]
