# Generated by Django 4.2.5 on 2023-11-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("artisans", "0006_service_service_individual_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtisanService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artisan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="artisans.artisan",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="artisans.service",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="artisan",
            name="services",
        ),
        migrations.AddField(
            model_name="artisan",
            name="services",
            field=models.ManyToManyField(
                through="artisans.ArtisanService", to="artisans.service"
            ),
        ),
    ]
