# Generated by Django 4.2.5 on 2023-11-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0007_artisanservice_alter_artisan_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='country',
        ),
        migrations.RemoveField(
            model_name='artisan',
            name='state',
        ),
    ]
